import type {Metadata} from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import {Providers} from "./providers";
import Head from "next/head";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Happy birthday",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <>
      <Head>
        <meta name="google" content="notranslate" />
      </Head>
      <html lang="es" className="light">
        <body>
          <Providers>{children}</Providers>
        </body>
      </html>
    </>
  );
}
